# Generated by Django 4.0.2 on 2022-05-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата комментария'),
        ),
    ]
